name: 'Structurizr Exporter'
description: 'Export Structurizr architecture diagrams to SVG format automatically. No setup required - just point to your .dsl files!'
author: 'heavywater-dev'
inputs:
  structurizr-path:
    description: 'Path to Structurizr workspace folder'
    required: false
    default: 'docs/structurizr/'
  output-path:
    description: 'Directory to store exported SVG images'
    required: false
    default: 'docs/images/'
  structurizr-version:
    description: 'Structurizr Lite Docker version'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm

    - name: Install TypeScript
      run: pnpm add -g typescript
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Create temporary node_modules folder
      run: mkdir -p ./temp_node_modules
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Install tsx temporarily
      run: pnpm add tsx --prefix ./temp_node_modules
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Install Playwright temporarily
      run: pnpm add playwright --prefix ./temp_node_modules
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Install Playwright Browsers
      run: ./temp_node_modules/.bin/playwright install --with-deps
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Start Structurizr Lite
      run: docker run -d --rm -p 8080:8080 -v "${{ github.workspace }}/${{ inputs.structurizr-path }}:/usr/local/structurizr" structurizr/lite:${{ inputs.structurizr-version }}
      working-directory: ${{ github.workspace }}
      shell: bash

    - name: Export Structurizr Diagrams
      run: ./temp_node_modules/.bin/tsx src/index.ts
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        INPUT_STRUCTURIZR_PATH: ${{ inputs.structurizr-path }}
        INPUT_OUTPUT_PATH: ${{ inputs.output-path }}

    - name: Stop Structurizr Lite
      run: docker stop $(docker ps -q --filter ancestor=structurizr/lite) || true
      working-directory: ${{ github.workspace }}
      shell: bash
branding:
  icon: 'layers'
  color: 'blue'
